rm: add feature to never prompt for removal of the custom home directory

diff --git a/distrobox-rm b/distrobox-rm
--- a/distrobox-rm
+++ b/distrobox-rm
@@ -51,6 +51,7 @@ non_interactive=0
 [ "$(id -ru)" -eq 0 ] && rootful=1 || rootful=0
 verbose=0
 rm_home=0
+never_rm_home=0
 response_rm_home="N"
 response_rm_exports="N"
 version="1.7.1.0"
@@ -321,6 +322,7 @@ cleanup_exports() {
 #   non_interactive   = bool non interactive mode
 #   force_flag = bool force mode
 #   rm_home    = bool remove home
+#	never_rm_home	= bool don't prompt to remove home
 #   verbose    = bool verbose
 # Outputs:
 #   none.
@@ -336,36 +338,41 @@ delete_container() {
 		return
 	fi
 
-	# Retrieve container's HOME, and check if it's different from host's one. In
-	# this case we prompt for deletion of the custom home.
-	container_home=$(${container_manager} inspect --type container --format \
-		'{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}{{slice . 5}}{{end}}{{end}}' "${container_name}")
-	# Prompt for confirmation
-	if [ "${container_home}" != "${HOME}" ]; then
-		if [ "${non_interactive}" -eq 0 ] &&
-			[ "${rm_home}" -eq 1 ]; then
+	# Check if we should prompt for removal of custom home directory
+	if [ ${never_rm_home} -eq 1 ]; then
+		rm_home_local=0
+	else
+		# Retrieve container's HOME, and check if it's different from host's one. In
+		# this case we prompt for deletion of the custom home.
+		container_home=$(${container_manager} inspect --type container --format \
+			'{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}{{slice . 5}}{{end}}{{end}}' "${container_name}")
+		# Prompt for confirmation
+		if [ "${container_home}" != "${HOME}" ]; then
+			if [ "${non_interactive}" -eq 0 ] &&
+				[ "${rm_home}" -eq 1 ]; then
 
-			printf "Do you want to remove custom home of container %s (%s)? [y/N]: " "${container_name}" "${container_home}"
-			read -r response_rm_home
-			response_rm_home="${response_rm_home:-"N"}"
+				printf "Do you want to remove custom home of container %s (%s)? [y/N]: " "${container_name}" "${container_home}"
+				read -r response_rm_home
+				response_rm_home="${response_rm_home:-"N"}"
+			fi
 		fi
-	fi
 
-	# Validate home response
-	# Accept only y,Y,Yes,yes,n,N,No,no.
-	case "${response_rm_home}" in
-		y | Y | Yes | yes | YES)
-			rm_home_local=1
-			;;
-		n | N | No | no | NO)
-			rm_home_local=0
-			;;
-		*) # Default case: If no more options then break out of the loop.
-			printf >&2 "Invalid input.\n"
-			printf >&2 "The available choices are: y,Y,Yes,yes,YES or n,N,No,no,NO.\nExiting.\n"
-			exit 1
-			;;
-	esac
+		# Validate home response
+		# Accept only y,Y,Yes,yes,n,N,No,no.
+		case "${response_rm_home}" in
+			y | Y | Yes | yes | YES)
+				rm_home_local=1
+				;;
+			n | N | No | no | NO)
+				rm_home_local=0
+				;;
+			*) # Default case: If no more options then break out of the loop.
+				printf >&2 "Invalid input.\n"
+				printf >&2 "The available choices are: y,Y,Yes,yes,YES or n,N,No,no,NO.\nExiting.\n"
+				exit 1
+				;;
+		esac
+	fi
 
 	rm_exports=0
 	if [ "${container_status}" != "running" ] && [ "${non_interactive}" -eq 0 ]; then
